name: amoi
description: Amoi groupe by Bô studio MADAGASCAR
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 0.1.1+1

environment:
  sdk: '>=2.18.0-271.2.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.6
  smooth_page_indicator: ^1.0.0+2
  firebase_core: ^2.3.0
  cloud_firestore: ^4.1.0
  flutter_easyloading: ^3.0.5
  connectivity_plus: ^3.0.2
  intl: ^0.17.0
  firebase_storage: ^11.0.10
  image_picker: ^0.8.6+1
  video_player: ^2.5.1
  toast: ^0.3.0
  path_provider_android: ^2.0.24
  flutter_icons: ^1.1.0
  permission_handler: ^10.2.0
  package_info: ^2.0.2
  path_provider: ^2.0.14
  url_launcher: ^6.1.10
  flutter_staggered_grid_view: ^0.6.2
  app_installer: ^1.1.0
  flutter_simple_treeview: ^3.0.2


  
flutter_native_splash:
  image: assets/logo/logosplashscreen.png
  color: "#000000"  # bleu -> #42a5f5
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/logo/
  - assets/money/
  - assets/webview/
  - assets/webview/src/
