// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6UcUKFpIW8QmLKT-bSICEmfaljMemmZE',
    appId: '1:635339364425:web:faeeb44a5c569d953f4798',
    messagingSenderId: '635339364425',
    projectId: 'amoi-groupe-bo',
    authDomain: 'amoi-groupe-bo.firebaseapp.com',
    storageBucket: 'amoi-groupe-bo.appspot.com',
    measurementId: 'G-8KC4HN3L47',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeCCQgCbsU7OxFPTirbczms-x6FWNRo64',
    appId: '1:635339364425:android:ff3f33ae1af7dfce3f4798',
    messagingSenderId: '635339364425',
    projectId: 'amoi-groupe-bo',
    storageBucket: 'amoi-groupe-bo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9O7M8BR_hL5tPBls7cR8ypWw5ukVpaXw',
    appId: '1:635339364425:ios:5b096eded41ec4103f4798',
    messagingSenderId: '635339364425',
    projectId: 'amoi-groupe-bo',
    storageBucket: 'amoi-groupe-bo.appspot.com',
    iosClientId: '635339364425-g4fv6nvdoscpgg2d23egqjhm8r50v2ul.apps.googleusercontent.com',
    iosBundleId: 'bo.studio.amoi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9O7M8BR_hL5tPBls7cR8ypWw5ukVpaXw',
    appId: '1:635339364425:ios:5b096eded41ec4103f4798',
    messagingSenderId: '635339364425',
    projectId: 'amoi-groupe-bo',
    storageBucket: 'amoi-groupe-bo.appspot.com',
    iosClientId: '635339364425-g4fv6nvdoscpgg2d23egqjhm8r50v2ul.apps.googleusercontent.com',
    iosBundleId: 'bo.studio.amoi',
  );
}
